using Microsoft.AspNetCore.Http.Features;
using Microsoft.Extensions.FileProviders;

var builder = WebApplication.CreateBuilder(args);

// 1. --- Service Configuration ---

// Adds services for API controllers.
builder.Services.AddControllers();

// Configures the maximum request body size, essential for your file uploads.
builder.Services.Configure<FormOptions>(options =>
{
    // Set the limit to 50 MB
    options.MultipartBodyLengthLimit = 50_000_000;
});

// Configures Cross-Origin Resource Sharing (CORS).
// This is crucial for allowing your React development server (e.g., on localhost:5173)
// to make requests to this API during development.
builder.Services.AddCors(options =>
{
    options.AddPolicy("FrontendPolicy", policy =>
    {
        policy
            .AllowAnyHeader()
            .AllowAnyMethod()
            .WithOrigins(
                // Keep your original URLs for any other clients
                "https://localhost:7240",
                "http://localhost:5122",
                "https://localhost:7288",
                "http://localhost:5284",
                // Add the default URL for the Vite React development server
                "http://localhost:5173"
            );
    });
});

var app = builder.Build();

// 2. --- Middleware Pipeline Configuration ---

// Use detailed error pages in the development environment.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

// Redirect HTTP requests to HTTPS.
app.UseHttpsRedirection();

// --- START: Configuration for Serving the React Frontend ---

// This section configures the app to serve the static files (HTML, JS, CSS)
// generated by the `npm run build` command in your React project.

// Define the absolute path to the 'dist' folder of your React project.
// It assumes the React project folder is a sibling to the API project folder.
var reactAppPath = Path.GetFullPath(Path.Combine(builder.Environment.ContentRootPath, "../SafeSpaces.React.Frontend/dist"));

// 3. Serve static files from the React build output.
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(reactAppPath),
    RequestPath = "" // Serve files from the root URL path
});

// --- END: Configuration for Serving the React Frontend ---

// 4. Apply the CORS policy. This must be placed before MapControllers.
app.UseCors("FrontendPolicy");

// 5. Map the API controller routes (e.g., /api/recordings/upload).
// The server will match API requests first.
app.MapControllers();

// 6. Configure a fallback route.
// For any request that doesn't match an API route or a static file,
// serve the 'index.html' from the React app. This is essential for
// client-side routing (e.g., React Router) to work correctly.
app.MapFallbackToFile(Path.Combine(reactAppPath, "index.html"));

// 7. Run the application.
app.Run();